# 🕵️ Chapter 1
# First Look at the Dataset

Before cleaning data, every data analyst spends time understanding the dataset.

In this notebook we will:

✅ Load the dataset

✅ Explore its structure

✅ Understand the columns

✅ Identify possible issues

Without changing a single value.

In [17]:
# ==========================================
# Import Libraries
# ==========================================

import pandas as pd
import numpy as np

In [18]:
# ==========================================
# Load Dataset
# ==========================================

df = pd.read_csv("dataset/employee_dirty_data.csv")

# Create Backup Copy
raw_df = df.copy()

# 👀 Take Your First Look

Let's see what our dataset looks like.

In [19]:
# First Five Rows
df.head()

# Last Five Rows
df.tail()

# Random Sample
df.sample(5)

# 📦 Dataset Shape
df.shape

# 🧾 Column Names
df.columns

# 🔍 Data Types
df.dtypes

# 📋 Dataset Summary
df.info()

# 📊 Numerical Summary
df.describe()

# 📊 Complete Summary
df.describe(include="all")

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   employee_id        100 non-null    int64
 1   full_name          100 non-null    str
 2   gender             100 non-null    str
 3   age                100 non-null    str
 4   email              52 non-null     str
 5   phone              100 non-null    str
 6   department         100 non-null    str
 7   designation        100 non-null    str
 8   salary             100 non-null    str
 9   bonus              81 non-null     float64
 10  experience         100 non-null    str
 11  joining_date       100 non-null    str
 12  last_promotion     33 non-null     str
 13  city               100 non-null    str
 14  state              100 non-null    str
 15  country            100 non-null    str
 16  zipcode            100 non-null    str
 17  performance_score  100 non-null    float64
 18  attendance         100 non-null    int64
 19  is_active          100 non-null    str
 20  project_count      81 non-null     float64
 21  manager            100 non-null    str
 22  remarks            100 non-null    str
dtypes: float64(3), int64(2), str(18)
memory usage: 18.1 KB

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
count,100.000000,100,100,100,52,100,100,100,100,81.00000,...,100,100,100,100,100.0000,100.00000,100,81.000000,100,100
unique,NaN,4,4,4,3,4,4,4,4,NaN,...,4,3,4,4,NaN,NaN,4,NaN,4,4
top,NaN,Bob Lee,MALE,35,johndoe@gmail,999999999999,Finance,Manager,75k,NaN,...,Delhi,Delhi,INDIA,110001,NaN,NaN,Y,NaN,Priya,Promoted
freq,NaN,48,48,48,19,48,48,48,48,NaN,...,48,48,48,48,NaN,NaN,48,NaN,48,48
mean,1035.240000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5006.17284,...,NaN,NaN,NaN,NaN,6.7460,77.44000,NaN,3.950617,NaN,NaN
std,31.416434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1443.72311,...,NaN,NaN,NaN,NaN,5.7712,45.10332,NaN,1.312452,NaN,NaN
min,1001.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2500.00000,...,NaN,NaN,NaN,NaN,-5.0000,-15.00000,NaN,2.000000,NaN,NaN
25%,1004.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5000.00000,...,NaN,NaN,NaN,NaN,8.5000,95.00000,NaN,3.000000,NaN,NaN
50%,1028.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6000.00000,...,NaN,NaN,NaN,NaN,9.2000,98.00000,NaN,5.000000,NaN,NaN
75%,1062.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6000.00000,...,NaN,NaN,NaN,NaN,9.2000,98.00000,NaN,5.000000,NaN,NaN
max,1100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6000.00000,...,NaN,NaN,NaN,NaN,11.0000,105.00000,NaN,5.000000,NaN,NaN

# 🎯 Observation Time

Congratulations!

You have successfully explored the dataset.

Without cleaning anything, carefully observe the outputs above.

Try to identify:

- Missing values
- Incorrect data types
- Duplicate records
- Inconsistent categories
- Strange values
- Columns that need further investigation

Remember,

A good Data Analyst first **observes** the data,

then creates a cleaning strategy.

# 🔍 Dataset Audit

---

## 🎯 Objective

Before cleaning any dataset, we need to inspect its quality.

A Data Audit helps us answer questions like:

- How many missing values are there?
- Are there duplicate records?
- What are the data types?
- Which columns have the most unique values?
- Which columns need immediate attention?

Think of this step as a **Health Checkup** for your dataset.

> **Rule #2:** Always audit your data before cleaning it.

In [20]:
# ==========================================
# 📊 Display Complete Dataset Information
# ==========================================

df.info()

# ==========================================
# 📋 Check Data Types
# ==========================================

df.dtypes

# ==========================================
# 📏 Dataset Dimensions
# ==========================================

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

# ==========================================
# 🏷️ Display All Column Names
# ==========================================

df.columns.tolist()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   employee_id        100 non-null    int64
 1   full_name          100 non-null    str
 2   gender             100 non-null    str
 3   age                100 non-null    str
 4   email              52 non-null     str
 5   phone              100 non-null    str
 6   department         100 non-null    str
 7   designation        100 non-null    str
 8   salary             100 non-null    str
 9   bonus              81 non-null     float64
 10  experience         100 non-null    str
 11  joining_date       100 non-null    str
 12  last_promotion     33 non-null     str
 13  city               100 non-null    str
 14  state              100 non-null    str
 15  country            100 non-null    str
 16  zipcode            100 non-null    str
 17  performance_score  100 non-null    float64
 18  attendance         100 non-null    int64
 19  is_active          100 non-null    str
 20  project_count      81 non-null     float64
 21  manager            100 non-null    str
 22  remarks            100 non-null    str
dtypes: float64(3), int64(2), str(18)
memory usage: 18.1 KB
Rows    : 100
Columns : 23

['employee_id',
 'full_name',
 'gender',
 'age',
 'email',
 'phone',
 'department',
 'designation',
 'salary',
 'bonus',
 'experience',
 'joining_date',
 'last_promotion',
 'city',
 'state',
 'country',
 'zipcode',
 'performance_score',
 'attendance',
 'is_active',
 'project_count',
 'manager',
 'remarks']

# ❓ Are There Any Missing Values?

# Missing values are one of the most common problems in real-world datasets.
# Let's find out how many missing values each column contains.

In [21]:
# ==========================================
# 🔍 Missing Values Count
# ==========================================

df.isnull().sum()

# ==========================================
# 📊 Missing Values Percentage
# ==========================================

(df.isnull().sum() / len(df) * 100).round(2)

# ==========================================
# 📋 Missing Value Report
# ==========================================

missing_report = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum()/len(df)*100).round(2)
})

missing_report.sort_values(
    by="Missing Values",
    ascending=False
)

                   Missing Values  Percentage
last_promotion                 67        67.0
email                          48        48.0
bonus                          19        19.0
project_count                  19        19.0
gender                          0         0.0
full_name                       0         0.0
employee_id                     0         0.0
department                      0         0.0
phone                           0         0.0
age                             0         0.0
salary                          0         0.0
experience                      0         0.0
joining_date                    0         0.0
city                            0         0.0
designation                     0         0.0
state                           0         0.0
country                         0         0.0
performance_score               0         0.0
zipcode                         0         0.0
attendance                      0         0.0
is_active                       0         0.0
manager                         0         0.0
remarks                         0         0.0

# 🔁 Duplicate Records

Duplicate records increase dataset size and may lead to incorrect analysis.

Let's check if our dataset contains duplicate rows.

In [22]:
# ==========================================
# 🔁 Total Duplicate Rows
# ==========================================

df.duplicated().sum()

# ==========================================
# 👀 Display Duplicate Rows
# ==========================================

df[df.duplicated()]

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
4,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
6,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
16,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
18,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
19,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
27,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
31,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
36,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
39,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
44,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
47,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
49,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
50,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
51,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
55,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
64,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
69,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
71,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
74,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
77,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
82,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
88,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
91,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
93,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
94,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
95,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
96,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
98,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

# 🎯 Unique Values

Knowing the number of unique values helps us identify:

- Categorical columns
- High-cardinality columns
- Possible inconsistencies

In [23]:
# ==========================================
# 🔢 Unique Values Per Column
# ==========================================

df.nunique()

# ==========================================
# 📊 Unique Value Report
# ==========================================

unique_report = pd.DataFrame({
    "Unique Values": df.nunique(),
    "Data Type": df.dtypes
})

unique_report

                   Unique Values Data Type
employee_id                   72     int64
full_name                      4       str
gender                         4       str
age                            4       str
email                          3       str
phone                          4       str
department                     4       str
designation                    4       str
salary                         4       str
bonus                          3   float64
experience                     4       str
joining_date                   4       str
last_promotion                 2       str
city                           4       str
state                          3       str
country                        4       str
zipcode                        4       str
performance_score              4   float64
attendance                     4     int64
is_active                      4       str
project_count                  3   float64
manager                        4       str
remarks                        4       str

# 📈 Statistical Summary

Let's inspect the numerical columns.

This helps us identify:

- Minimum values
- Maximum values
- Mean
- Standard Deviation
- Possible Outliers

In [24]:
# ==========================================
# 📊 Numerical Summary
# ==========================================

df.describe()

# ==========================================
# 📊 Complete Summary
# ==========================================

df.describe(include="all")

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
count,100.000000,100,100,100,52,100,100,100,100,81.00000,...,100,100,100,100,100.0000,100.00000,100,81.000000,100,100
unique,NaN,4,4,4,3,4,4,4,4,NaN,...,4,3,4,4,NaN,NaN,4,NaN,4,4
top,NaN,Bob Lee,MALE,35,johndoe@gmail,999999999999,Finance,Manager,75k,NaN,...,Delhi,Delhi,INDIA,110001,NaN,NaN,Y,NaN,Priya,Promoted
freq,NaN,48,48,48,19,48,48,48,48,NaN,...,48,48,48,48,NaN,NaN,48,NaN,48,48
mean,1035.240000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5006.17284,...,NaN,NaN,NaN,NaN,6.7460,77.44000,NaN,3.950617,NaN,NaN
std,31.416434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1443.72311,...,NaN,NaN,NaN,NaN,5.7712,45.10332,NaN,1.312452,NaN,NaN
min,1001.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2500.00000,...,NaN,NaN,NaN,NaN,-5.0000,-15.00000,NaN,2.000000,NaN,NaN
25%,1004.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5000.00000,...,NaN,NaN,NaN,NaN,8.5000,95.00000,NaN,3.000000,NaN,NaN
50%,1028.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6000.00000,...,NaN,NaN,NaN,NaN,9.2000,98.00000,NaN,5.000000,NaN,NaN
75%,1062.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6000.00000,...,NaN,NaN,NaN,NaN,9.2000,98.00000,NaN,5.000000,NaN,NaN
max,1100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6000.00000,...,NaN,NaN,NaN,NaN,11.0000,105.00000,NaN,5.000000,NaN,NaN

# 📋 Data Quality Report

Let's combine everything into a single report.

This report provides a quick overview of the dataset's quality.

In [25]:
# ==========================================
# 📑 Data Quality Report
# ==========================================

quality_report = pd.DataFrame({
    "Data Type": df.dtypes,
    "Missing Values": df.isnull().sum(),
    "Missing %": (df.isnull().sum()/len(df)*100).round(2),
    "Unique Values": df.nunique(),
    "Duplicate Values": [df[col].duplicated().sum() for col in df.columns]
})

quality_report

,Data Type,Missing Values,Missing %,Unique Values,Duplicate Values
employee_id,int64,0,0.0,72,28
full_name,str,0,0.0,4,96
gender,str,0,0.0,4,96
age,str,0,0.0,4,96
email,str,48,48.0,3,96
phone,str,0,0.0,4,96
department,str,0,0.0,4,96
designation,str,0,0.0,4,96
salary,str,0,0.0,4,96
bonus,float64,19,19.0,3,96
experience,str,0,0.0,4,96
joining_date,str,0,0.0,4,96
last_promotion,str,67,67.0,2,97
city,str,0,0.0,4,96
state,str,0,0.0,3,97
country,str,0,0.0,4,96
zipcode,str,0,0.0,4,96
performance_score,float64,0,0.0,4,96
attendance,int64,0,0.0,4,96
is_active,str,0,0.0,4,96
project_count,float64,19,19.0,3,96
manager,str,0,0.0,4,96
remarks,str,0,0.0,4,96

# 📝 Observations

Before moving to the next notebook, answer these questions:

- Which column has the highest number of missing values?
- Which columns have incorrect data types?
- Which columns contain duplicate values?
- Which columns have inconsistent categories?
- Which columns appear to contain outliers?

Do not clean anything yet.

The goal of this notebook is only to understand the quality of the dataset.