# 🕳️ Chapter 02 - Missing Values

---

# 🎯 Objective

Missing values are one of the most common problems in real-world datasets.

A missing value simply means that some information is unavailable or was not recorded.

Examples:

- Customer forgot to enter their phone number.
- Salary is not available.
- Email address is missing.
- Date of joining is unknown.

If we don't handle missing values properly, they can lead to:

❌ Incorrect Analysis

❌ Wrong Machine Learning Predictions

❌ Runtime Errors

❌ Poor Data Quality

In this chapter, we will learn every important technique used to identify and handle missing values.

> **Rule #1:** Never ignore missing values.

In [5]:
# ==========================================
# 📚 Import Libraries
# ==========================================

import pandas as pd
import numpy as np

In [6]:
# ==========================================
# 📂 Load Dataset
# ==========================================

df = pd.read_csv("dataset/employee_dirty_data.csv")

# Backup Copy
raw_df = df.copy()

# 🔍 Detect Missing Values

Before fixing missing values, we first need to identify them.

Pandas provides several useful functions for this purpose.

In [7]:
# ==========================================
# 🔍 Check Missing Values
# ==========================================

df.isnull()

# ==========================================
# 🔍 Check Missing Values (Alternative)
# ==========================================

df.isna()

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
98,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
99,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

# 📌 What is the Difference?

Both functions perform exactly the same task.

```python
df.isnull()
```

and

```python
df.isna()
```

produce identical results.

You can use whichever you prefer.

In [8]:
# ==========================================
# 📊 Count Missing Values
# ==========================================

df.isnull().sum()

# ==========================================
# 📊 Total Missing Values
# ==========================================

df.isnull().sum().sum()

# ==========================================
# 📈 Missing Value Percentage
# ==========================================

(df.isnull().sum()/len(df)*100).round(2)

# ==========================================
# 📋 Missing Value Report
# ==========================================

missing_report = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum()/len(df)*100).round(2)
})

missing_report.sort_values(
    by="Missing Values",
    ascending=False
)

                   Missing Values  Percentage
last_promotion                 67        67.0
email                          48        48.0
bonus                          19        19.0
project_count                  19        19.0
gender                          0         0.0
full_name                       0         0.0
employee_id                     0         0.0
department                      0         0.0
phone                           0         0.0
age                             0         0.0
salary                          0         0.0
experience                      0         0.0
joining_date                    0         0.0
city                            0         0.0
designation                     0         0.0
state                           0         0.0
country                         0         0.0
performance_score               0         0.0
zipcode                         0         0.0
attendance                      0         0.0
is_active                       0         0.0
manager                         0         0.0
remarks                         0         0.0

# 👀 Display Only Columns That Have Missing Values

Instead of displaying every column,

let's display only the columns that actually contain missing values.

In [9]:
# ==========================================
# 📋 Columns With Missing Values
# ==========================================

df.isnull().sum()[df.isnull().sum() > 0]

email             48
bonus             19
last_promotion    67
project_count     19
dtype: int64

# ❌ Display Rows That Contain Missing Values

Sometimes we need to inspect the actual rows containing missing values.

In [10]:
# ==========================================
# 🔍 Rows Containing Missing Values
# ==========================================

df[df.isnull().any(axis=1)]

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
3,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
6,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
7,1008,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
95,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
97,1098,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
98,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
99,1100,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

# ✅ Display Rows Without Missing Values

This is useful when we want to analyze only complete records.

In [11]:
# ==========================================
# ✅ Rows Without Missing Values
# ==========================================

df[df.notnull().all(axis=1)]

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
5,1006,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
9,1010,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
16,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
20,1021,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
22,1023,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
25,1026,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
29,1030,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
30,1031,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
35,1036,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
37,1038,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
41,1042,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
43,1044,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
44,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
46,1047,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
48,1049,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
57,1058,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
58,1059,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
61,1062,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
64,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
66,1067,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
70,1071,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
71,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
72,1073,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
75,1076,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
76,1077,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
77,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
83,1084,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
85,1086,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
87,1088,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
92,1093,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
96,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent

# 🎯 Observation

After running all the above code,

answer these questions:

- Which column has the highest number of missing values?
- Which column has no missing values?
- How many total missing values exist?
- Which rows require immediate attention?

⚠️ Do NOT remove missing values yet.

In the next section, we will learn every technique used to handle missing values.

# 🗑️ Removing Missing Values using `dropna()`

---

# 🎯 Objective

Sometimes a dataset contains rows or columns with missing values that are no longer useful.

Pandas provides the `dropna()` function to remove missing values from a dataset.

It can remove:

✅ Rows

✅ Columns

✅ Specific missing values

✅ Rows based on a threshold

> **Rule #2:** Never use `dropna()` blindly. Always understand how much data you are removing.

In [12]:
# ==========================================
# 📋 Display Missing Values
# ==========================================

df.isnull().sum()

employee_id           0
full_name             0
gender                0
age                   0
email                48
phone                 0
department            0
designation           0
salary                0
bonus                19
experience            0
joining_date          0
last_promotion       67
city                  0
state                 0
country               0
zipcode               0
performance_score     0
attendance            0
is_active             0
project_count        19
manager               0
remarks               0
dtype: int64

# 🚀 Remove Rows with Missing Values

By default, `dropna()` removes every row that contains at least one missing value.

### Syntax

```python
df.dropna()
```

In [13]:
# ==========================================
# 🗑️ Remove Rows with Missing Values
# ==========================================

df.dropna()

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
5,1006,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
9,1010,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
16,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
20,1021,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
22,1023,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
25,1026,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
29,1030,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
30,1031,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
35,1036,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
37,1038,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
41,1042,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
43,1044,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
44,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
46,1047,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
48,1049,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
57,1058,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
58,1059,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
61,1062,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
64,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
66,1067,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
70,1071,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
71,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
72,1073,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
75,1076,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
76,1077,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
77,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
83,1084,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
85,1086,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
87,1088,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
92,1093,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
96,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent

In [14]:
# ==========================================
# 🗑️ Save Result into New DataFrame
# ==========================================

clean_df = df.dropna()

clean_df

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
5,1006,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
9,1010,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
16,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
20,1021,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
22,1023,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
25,1026,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
29,1030,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
30,1031,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
35,1036,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
37,1038,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
41,1042,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
43,1044,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
44,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
46,1047,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
48,1049,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
57,1058,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
58,1059,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
61,1062,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
64,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
66,1067,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
70,1071,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
71,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
72,1073,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
75,1076,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
76,1077,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
77,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
83,1084,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
85,1086,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
87,1088,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
92,1093,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
96,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent

# 📊 Compare Dataset Size

Always compare the dataset before and after removing rows.

In [15]:
# ==========================================
# 📏 Original Dataset Shape
# ==========================================

df.shape

# ==========================================
# 📏 Dataset Shape After dropna()
# ==========================================

clean_df.shape

(33, 23)

# 🚀 Remove Columns with Missing Values

Instead of removing rows,

we can remove columns containing missing values.

### Syntax

```python
df.dropna(axis=1)
```

`axis=1`

means remove columns.

In [16]:
# ==========================================
# 🗑️ Remove Columns Having Missing Values
# ==========================================

df.dropna(axis=1)

,employee_id,full_name,gender,age,phone,department,designation,salary,experience,joining_date,city,state,country,zipcode,performance_score,attendance,is_active,manager,remarks
0,1001,John Smith,Male,28,9876543210,HR,Analyst,55000,3,2022-01-15,Mumbai,Maharashtra,India,400001,8.5,95,Yes,Rahul Sharma,Good Employee
1,1002,John Doe,male,Thirty,98765,hr,Data Analyst,"$45,000",Five Years,15/02/2022,mumbai,MH,IND,4000A,11.0,105,TRUE,Amit,
2,1003,Alice@@ Brown,F,-25,ABCDE12345,Human Resource,Developer,-25000,-2,31/02/2023,Pune,Maharashtra,india,411001,-5.0,-15,1,Suresh,Excellent
3,1004,Bob Lee,MALE,35,999999999999,Finance,Manager,75k,10 Years,"May 20, 2020",Delhi,Delhi,INDIA,110001,9.2,98,Y,Priya,Promoted
4,1004,Bob Lee,MALE,35,999999999999,Finance,Manager,75k,10 Years,"May 20, 2020",Delhi,Delhi,INDIA,110001,9.2,98,Y,Priya,Promoted
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1004,Bob Lee,MALE,35,999999999999,Finance,Manager,75k,10 Years,"May 20, 2020",Delhi,Delhi,INDIA,110001,9.2,98,Y,Priya,Promoted
96,1003,Alice@@ Brown,F,-25,ABCDE12345,Human Resource,Developer,-25000,-2,31/02/2023,Pune,Maharashtra,india,411001,-5.0,-15,1,Suresh,Excellent
97,1098,John Doe,male,Thirty,98765,hr,Data Analyst,"$45,000",Five Years,15/02/2022,mumbai,MH,IND,4000A,11.0,105,TRUE,Amit,
98,1004,Bob Lee,MALE,35,999999999999,Finance,Manager,75k,10 Years,"May 20, 2020",Delhi,Delhi,INDIA,110001,9.2,98,Y,Priya,Promoted
99,1100,Bob Lee,MALE,35,999999999999,Finance,Manager,75k,10 Years,"May 20, 2020",Delhi,Delhi,INDIA,110001,9.2,98,Y,Priya,Promoted

# 🚀 Remove Rows Only If All Values Are Missing

Sometimes a row contains only missing values.

In that case we can remove only those rows.

### Syntax

```python
df.dropna(how="all")
```

In [17]:
# ==========================================
# 🗑️ Remove Rows Where Every Value is Missing
# ==========================================

df.dropna(how="all")

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
96,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
97,1098,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
98,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
99,1100,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

# 🚀 Remove Rows If Any Value is Missing

This is the default behavior.

### Syntax

```python
df.dropna(how="any")
```

In [18]:
# ==========================================
# 🗑️ Remove Rows Having At Least One Missing Value
# ==========================================

df.dropna(how="any")

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
5,1006,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
9,1010,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
16,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
20,1021,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
22,1023,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
25,1026,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
29,1030,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
30,1031,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
35,1036,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
37,1038,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
41,1042,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
43,1044,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
44,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
46,1047,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
48,1049,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
57,1058,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
58,1059,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
61,1062,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
64,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
66,1067,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
70,1071,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
71,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
72,1073,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
75,1076,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
76,1077,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
77,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
83,1084,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
85,1086,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
87,1088,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
92,1093,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
96,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent

# 🚀 Remove Missing Values from Specific Columns

Sometimes we only care about important columns.

For example,

if the **Email** column is missing,

remove only those rows.

In [19]:
# ==========================================
# 🗑️ Remove Rows Where Email is Missing
# ==========================================

df.dropna(subset=["email"])

# ==========================================
# 🗑️ Remove Rows Where Salary is Missing
# ==========================================

df.dropna(subset=["salary"])

# ==========================================
# 🗑️ Remove Rows Where Email and Salary are Missing
# ==========================================

df.dropna(subset=["email", "salary"])

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
5,1006,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
6,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
7,1008,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
9,1010,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
16,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
18,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
20,1021,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
22,1023,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
25,1026,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
26,1027,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
28,1029,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
29,1030,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
30,1031,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
31,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
34,1035,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
35,1036,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
37,1038,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
41,1042,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
43,1044,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
44,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
46,1047,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
48,1049,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
49,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
57,1058,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
58,1059,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
61,1062,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
64,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
66,1067,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
70,1071,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
71,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
72,1073,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
73,1074,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
74,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
75,1076,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
76,1077,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
77,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
79,1080,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
81,1082,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
83,1084,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
84,1085,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
85,1086,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
86,1087,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
87,1088,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
89,1090,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
92,1093,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
93,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
94,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
96,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
97,1098,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,

# 🚀 Keep Rows Having Minimum Non-Missing Values

The `thresh` parameter keeps rows having at least a specified number of non-missing values.

### Syntax

```python
df.dropna(thresh=20)
```

If a row has fewer than 20 valid values,

it will be removed.

In [20]:
# ==========================================
# 🗑️ Keep Rows with At Least 20 Non-Missing Values
# ==========================================

df.dropna(thresh=20)

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
96,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
97,1098,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
98,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
99,1100,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

# 🚀 Modify the Original Dataset

Normally,

`dropna()` returns a new DataFrame.

To permanently modify the original dataset,

use:

```python
inplace=True
```

⚠️ Use this carefully because it cannot be undone.

In [21]:
# ==========================================
# 🗑️ Permanently Remove Missing Values
# ==========================================

temp_df = df.copy()

temp_df.dropna(inplace=True)

temp_df

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
5,1006,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
9,1010,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
16,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
20,1021,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
22,1023,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
25,1026,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
29,1030,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
30,1031,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
35,1036,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
37,1038,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
41,1042,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
43,1044,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
44,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
46,1047,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
48,1049,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
57,1058,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
58,1059,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
61,1062,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
64,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
66,1067,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
70,1071,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
71,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
72,1073,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
75,1076,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
76,1077,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
77,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
83,1084,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
85,1086,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
87,1088,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
92,1093,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
96,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent

# 🎯 Summary

In this section, you learned:

✅ `dropna()`

✅ `axis`

✅ `how`

✅ `subset`

✅ `thresh`

✅ `inplace`

You can now safely remove missing values based on different conditions.

In the next section, we will learn how to **replace missing values** using the `fillna()` function instead of deleting data.

# ✍️ Filling Missing Values using `fillna()`

---

# 🎯 Objective

Removing missing values is **not always the best solution**.

Sometimes deleting rows or columns can result in losing valuable information.

Instead of removing data, we can replace missing values with meaningful values using the **`fillna()`** function.

Some common techniques include:

✅ Fill with a constant value

✅ Fill with Mean

✅ Fill with Median

✅ Fill with Mode

✅ Forward Fill

✅ Backward Fill

> **Rule #3:** If the data is important, try filling missing values before deleting them.

In [22]:
# ==========================================
# 📋 Check Missing Values
# ==========================================

df.isnull().sum()

employee_id           0
full_name             0
gender                0
age                   0
email                48
phone                 0
department            0
designation           0
salary                0
bonus                19
experience            0
joining_date          0
last_promotion       67
city                  0
state                 0
country               0
zipcode               0
performance_score     0
attendance            0
is_active             0
project_count        19
manager               0
remarks               0
dtype: int64

# 🚀 Fill Missing Values with a Constant

Sometimes we simply want to replace every missing value with the same value.

### Syntax

```python
df.fillna(value)
```

In [23]:
# ==========================================
# Replace Missing Values with 0
# ==========================================

df.fillna(0)

# ==========================================
# Replace Missing Values with "Unknown"
# ==========================================

df.fillna("Unknown")

# ==========================================
# Replace Missing Values with "Not Available"
# ==========================================

df.fillna("Not Available")

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",Not Available,...,mumbai,MH,IND,4000A,11.0,105,TRUE,Not Available,Amit,
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35,Not Available,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,Not Available,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1004,Bob Lee,MALE,35,Not Available,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
96,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
97,1098,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",Not Available,...,mumbai,MH,IND,4000A,11.0,105,TRUE,Not Available,Amit,
98,1004,Bob Lee,MALE,35,Not Available,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
99,1100,Bob Lee,MALE,35,Not Available,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

# 🚀 Fill Missing Values in a Specific Column

Instead of filling the entire dataset,

we can fill only one column.

In [24]:
# ==========================================
# Fill Missing Salary with 0
# ==========================================

df["salary"] = df["salary"].fillna(0)

df.head()

# ==========================================
# Fill Missing Email with "Unknown"
# ==========================================

df["email"] = df["email"].fillna("Unknown")

df.head()

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

# 🚀 Fill Missing Values with Mean

The **Mean** is the average of all numerical values.

Best used for:

✔️ Continuous Numerical Data

Example:

- Salary
- Age
- Bonus

In [25]:
# ==========================================
# Fill Missing Age with Mean
# ==========================================

temp_df = df.copy()

temp_df["age"] = pd.to_numeric(temp_df["age"], errors="coerce")

temp_df["age"] = temp_df["age"].fillna(temp_df["age"].mean())

temp_df.head()

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28.000000,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
1,1002,John Doe,male,19.716049,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
2,1003,Alice@@ Brown,F,-25.000000,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35.000000,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35.000000,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

# 🚀 Fill Missing Values with Median

The **Median** is the middle value after sorting.

It is useful when the dataset contains outliers.

Best used for:

✔️ Salary

✔️ Income

✔️ Property Price

In [26]:
# ==========================================
# Fill Missing Salary with Median
# ==========================================

temp_df = df.copy()

temp_df["salary"] = pd.to_numeric(
    temp_df["salary"],
    errors="coerce"
)

temp_df["salary"] = temp_df["salary"].fillna(
    temp_df["salary"].median()
)

temp_df.head()

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000.0,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,-25000.0,NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,-25000.0,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,-25000.0,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

# 🚀 Fill Missing Values with Mode

The **Mode** is the most frequently occurring value.

Best used for:

✔️ Gender

✔️ City

✔️ Country

✔️ Department

In [27]:
# ==========================================
# Fill Missing Department with Mode
# ==========================================

temp_df = df.copy()

temp_df["department"] = temp_df["department"].fillna(
    temp_df["department"].mode()[0]
)

temp_df.head()

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

In [28]:
# ==========================================
# Fill Missing Gender with Mode
# ==========================================

temp_df = df.copy()

temp_df["gender"] = temp_df["gender"].fillna(
    temp_df["gender"].mode()[0]
)

temp_df.head()

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

# 🚀 Fill Different Columns with Different Values

We can fill multiple columns at once by passing a dictionary.

In [29]:
# ==========================================
# Fill Multiple Columns
# ==========================================

temp_df = df.copy()

temp_df.fillna({
    "salary": 0,
    "email": "Unknown",
    "department": "Not Assigned",
    "city": "Unknown"
})

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
96,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
97,1098,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
98,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
99,1100,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

# 🚀 Permanently Save Changes

The `inplace=True` parameter updates the original DataFrame directly.

⚠️ Use it carefully because the changes cannot be undone.

In [30]:
# ==========================================
# Permanently Fill Missing Values
# ==========================================

temp_df = df.copy()

temp_df["department"].fillna(
    "Unknown",
    inplace=True
)

temp_df.head()

C:\Users\VAISHNAVI\AppData\Local\Temp\ipykernel_11540\4066843348.py:7: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  temp_df["department"].fillna(

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

# 🎯 Summary

You have learned:

✅ `fillna()`

✅ Fill with Constant Value

✅ Fill with Mean

✅ Fill with Median

✅ Fill with Mode

✅ Fill Multiple Columns

✅ `inplace=True`

In the next section, we will learn **Forward Fill (`ffill`)**, **Backward Fill (`bfill`)**, and **Interpolation**, which are widely used for time-series and sequential datasets.

# ⏩ Forward Fill (`ffill`)

---

# 🎯 Objective

Forward Fill copies the **previous valid value** into the missing value.

It is mainly used when the previous observation is expected to remain valid.

Common Use Cases:

✅ Time Series Data

✅ Stock Prices

✅ Sensor Data

✅ Attendance Records

> **Rule #4:** Use Forward Fill only when the previous value logically belongs to the next missing record.

In [31]:
# ==========================================
# 📋 Check Missing Values
# ==========================================

df.isnull().sum()

employee_id           0
full_name             0
gender                0
age                   0
email                 0
phone                 0
department            0
designation           0
salary                0
bonus                19
experience            0
joining_date          0
last_promotion       67
city                  0
state                 0
country               0
zipcode               0
performance_score     0
attendance            0
is_active             0
project_count        19
manager               0
remarks               0
dtype: int64

# 🚀 Forward Fill

### Syntax

```python
df.ffill()
```

or

```python
df.fillna(method="ffill")
```

In [32]:
# ==========================================
# Forward Fill Entire Dataset
# ==========================================

df.ffill()

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",5000.0,...,mumbai,MH,IND,4000A,11.0,105,TRUE,3.0,Amit,
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
96,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
97,1098,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",2500.0,...,mumbai,MH,IND,4000A,11.0,105,TRUE,2.0,Amit,
98,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
99,1100,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

In [33]:
# ==========================================
# Forward Fill a Single Column
# ==========================================

temp_df = df.copy()

temp_df["department"] = temp_df["department"].ffill()

temp_df.head(15)

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
5,1006,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
6,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
7,1008,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
8,1009,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
9,1010,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
10,1011,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
11,1012,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
12,1013,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
13,1014,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
14,1015,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

In [34]:
# ==========================================
# Forward Fill Salary Column
# ==========================================

temp_df = df.copy()

temp_df["salary"] = temp_df["salary"].ffill()

temp_df.head(15)

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
5,1006,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
6,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
7,1008,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
8,1009,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
9,1010,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
10,1011,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
11,1012,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
12,1013,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
13,1014,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
14,1015,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

# 🚀 Forward Fill with Limit

Sometimes we don't want to fill every missing value.

The **limit** parameter restricts how many consecutive missing values will be filled.

### Syntax

```python
df.ffill(limit=2)
```

In [35]:
# ==========================================
# Forward Fill with Limit
# ==========================================

df.ffill(limit=2)

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",5000.0,...,mumbai,MH,IND,4000A,11.0,105,TRUE,3.0,Amit,
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
96,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
97,1098,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",2500.0,...,mumbai,MH,IND,4000A,11.0,105,TRUE,2.0,Amit,
98,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
99,1100,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

# ⏪ Backward Fill (`bfill`)

---

# 🎯 Objective

Backward Fill copies the **next valid value** into the missing value.

Instead of looking upward,

it looks downward for the next available value.

Common Use Cases:

✅ Future Schedule

✅ Timetable

✅ Forecast Data

✅ Sequential Records

In [36]:
# ==========================================
# Backward Fill Entire Dataset
# ==========================================

df.bfill()

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",2500.0,...,mumbai,MH,IND,4000A,11.0,105,TRUE,2.0,Amit,
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
96,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
97,1098,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",6000.0,...,mumbai,MH,IND,4000A,11.0,105,TRUE,5.0,Amit,
98,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
99,1100,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

In [37]:
# ==========================================
# Backward Fill Department
# ==========================================

temp_df = df.copy()

temp_df["department"] = temp_df["department"].bfill()

temp_df.head(15)

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
5,1006,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
6,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
7,1008,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
8,1009,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
9,1010,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
10,1011,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
11,1012,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
12,1013,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
13,1014,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
14,1015,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

In [38]:
# ==========================================
# Backward Fill Salary
# ==========================================

temp_df = df.copy()

temp_df["salary"] = temp_df["salary"].bfill()

temp_df.head(15)

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
5,1006,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
6,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
7,1008,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
8,1009,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
9,1010,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
10,1011,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
11,1012,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
12,1013,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
13,1014,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
14,1015,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

# 🚀 Backward Fill with Limit

The **limit** parameter works the same as Forward Fill.

It limits the number of consecutive missing values that can be filled.

In [39]:
# ==========================================
# Backward Fill with Limit
# ==========================================

df.bfill(limit=2)

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",2500.0,...,mumbai,MH,IND,4000A,11.0,105,TRUE,2.0,Amit,
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
96,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
97,1098,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",6000.0,...,mumbai,MH,IND,4000A,11.0,105,TRUE,5.0,Amit,
98,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
99,1100,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

# 📈 Interpolation

---

# 🎯 Objective

Interpolation estimates missing values using nearby numerical values.

Instead of copying values,

it calculates a reasonable value.

Common Use Cases:

✅ Temperature

✅ Rainfall

✅ Sales

✅ Stock Prices

✅ Scientific Data

> Interpolation should only be used on **numerical columns**.

In [40]:
# ==========================================
# Check Numerical Columns
# ==========================================

df.select_dtypes(include="number").columns

Index(['employee_id', 'bonus', 'performance_score', 'attendance',
       'project_count'],
      dtype='str')

In [41]:
# ==========================================
# Interpolate Numerical Columns
# ==========================================

temp_df = df.copy()

numeric_columns = temp_df.select_dtypes(include="number").columns

temp_df[numeric_columns] = temp_df[numeric_columns].interpolate()

temp_df.head()

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",3750.0,...,mumbai,MH,IND,4000A,11.0,105,TRUE,2.5,Amit,
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

# 🚀 Different Interpolation Methods

Pandas supports multiple interpolation methods.

Some commonly used methods are:

- linear (Default)
- nearest
- quadratic
- cubic
- polynomial

The most commonly used method is **linear**.

In [42]:
# ==========================================
# Linear Interpolation
# ==========================================

temp_df = df.copy()

numeric_columns = temp_df.select_dtypes(include="number").columns

temp_df[numeric_columns] = temp_df[numeric_columns].interpolate(
    method="linear"
)

temp_df.head()

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",3750.0,...,mumbai,MH,IND,4000A,11.0,105,TRUE,2.5,Amit,
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

In [43]:
# ==========================================
# Nearest Interpolation
# ==========================================

temp_df = df.copy()

numeric_columns = temp_df.select_dtypes(include="number").columns

temp_df[numeric_columns] = temp_df[numeric_columns].interpolate(
    method="nearest"
)

temp_df.head()

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",5000.0,...,mumbai,MH,IND,4000A,11.0,105,TRUE,3.0,Amit,
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,Unknown,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

# 📝 Best Practices

✅ Use **Mean** for normally distributed numerical data.

✅ Use **Median** when numerical columns contain outliers.

✅ Use **Mode** for categorical columns.

✅ Use **Forward Fill** for sequential or time-series data.

✅ Use **Backward Fill** when the next value is more appropriate.

✅ Use **Interpolation** only for numerical continuous data.

❌ Never replace every missing value with **0** without understanding the data.

❌ Never use Forward Fill or Backward Fill randomly.

# 📌 Chapter 02 Complete ✅

Congratulations! 🎉

You have learned every major technique for handling missing values in Pandas.

Functions Covered:

- `isnull()`
- `isna()`
- `notnull()`
- `notna()`
- `dropna()`
- `fillna()`
- `ffill()`
- `bfill()`
- `interpolate()`

In the next chapter, we will learn **Duplicate Data Handling**, where we'll detect, analyze, and remove duplicate records using every important Pandas function.