# 🧹 Chapter 05 - String Cleaning

---

# 🎯 Objective

Text data is one of the messiest types of data found in real-world datasets.

Names, email addresses, phone numbers, cities, departments, and addresses often contain inconsistencies such as:

- Extra spaces
- Different letter cases
- Typing mistakes
- Special characters
- Mixed formatting
- Unwanted symbols

Before analyzing or training Machine Learning models, text data should always be cleaned and standardized.

In this chapter, we will learn every important string function provided by Pandas.

> **Rule #1:** Clean text data before performing analysis.

In [508]:
# ==========================================
# 📚 Import Libraries
# ==========================================

import pandas as pd
import numpy as np

In [509]:
# ==========================================
# 📂 Load Dataset
# ==========================================

df = pd.read_csv("dataset/employee_dirty_data.csv")

# Create Backup Copy
raw_df = df.copy()

# 👀 Display Sample Text Columns

Let's inspect the text columns before cleaning them.

In [510]:
# ==========================================
# Display Name Column
# ==========================================

df["full_name"].head(10)

# ==========================================
# Display Department Column
# ==========================================

df["department"].head(10)

# ==========================================
# Display Department Column
# ==========================================

df["department"].head(10)

# ==========================================
# Display City Column
# ==========================================

df["city"].head(10)

0    Mumbai
1    mumbai
2      Pune
3     Delhi
4     Delhi
5    Mumbai
6    mumbai
7    mumbai
8     Delhi
9      Pune
Name: city, dtype: str

# 🔠 Convert Text to Lowercase

Sometimes the same category appears in different letter cases.

Example

Sales

sales

SALES

These should all become

sales

### Syntax

```python
Series.str.lower()
```

In [511]:
# ==========================================
# Convert Name to Lowercase
# ==========================================

temp_df = df.copy()

temp_df["full_name"] = temp_df["full_name"].str.lower()

temp_df["full_name"].head(10)

# ==========================================
# Convert Department to Lowercase
# ==========================================

temp_df = df.copy()

temp_df["department"] = temp_df["department"].str.lower()

temp_df["department"].head(10)

0                hr
1                hr
2    human resource
3           finance
4           finance
5                hr
6                hr
7                hr
8           finance
9    human resource
Name: department, dtype: str

# 🔠 Convert Text to Uppercase

Converts every letter into uppercase.

### Syntax

```python
Series.str.upper()
```

In [512]:
# ==========================================
# Convert Name to Uppercase
# ==========================================

temp_df = df.copy()

temp_df["full_name"] = temp_df["full_name"].str.upper()

temp_df["full_name"].head(10)

# ==========================================
# Convert City to Uppercase
# ==========================================

temp_df = df.copy()

temp_df["city"] = temp_df["city"].str.upper()

temp_df["city"].head(10)

0    MUMBAI
1    MUMBAI
2      PUNE
3     DELHI
4     DELHI
5    MUMBAI
6    MUMBAI
7    MUMBAI
8     DELHI
9      PUNE
Name: city, dtype: str

# ✨ Convert Text to Title Case

Title Case capitalizes the first letter of every word.

Example

john doe

↓

John Doe

### Syntax

```python
Series.str.title()
```

In [513]:
# ==========================================
# Convert Name to Title Case
# ==========================================

temp_df = df.copy()

temp_df["full_name"] = temp_df["full_name"].str.title()

temp_df["full_name"].head(10)

# ==========================================
# Convert Department to Title Case
# ==========================================

temp_df = df.copy()

temp_df["department"] = temp_df["department"].str.title()

temp_df["department"].head(10)

0                Hr
1                Hr
2    Human Resource
3           Finance
4           Finance
5                Hr
6                Hr
7                Hr
8           Finance
9    Human Resource
Name: department, dtype: str

# 🔤 Capitalize First Letter

Only the first letter of the sentence becomes uppercase.

### Syntax

```python
Series.str.capitalize()
```

In [514]:
# ==========================================
# Capitalize Name
# ==========================================

temp_df = df.copy()

temp_df["full_name"] = temp_df["full_name"].str.capitalize()

temp_df["full_name"].head(10)

0       John smith
1        john doe
2    Alice@@ brown
3          Bob lee
4          Bob lee
5       John smith
6        john doe
7        john doe
8          Bob lee
9    Alice@@ brown
Name: full_name, dtype: str

# 🔄 Swap Letter Cases

Uppercase becomes lowercase.

Lowercase becomes uppercase.

### Syntax

```python
Series.str.swapcase()
```

In [515]:
# ==========================================
# Swap Letter Cases
# ==========================================

temp_df = df.copy()

temp_df["department"] = temp_df["department"].str.swapcase()

temp_df["department"].head(10)

0                hr
1                HR
2    hUMAN rESOURCE
3           fINANCE
4           fINANCE
5                hr
6                HR
7                HR
8           fINANCE
9    hUMAN rESOURCE
Name: department, dtype: str

# 📏 Calculate String Length

Find the number of characters present in each value.

### Syntax

```python
Series.str.len()
```

In [516]:
# ==========================================
# Length of Employee Names
# ==========================================

df["full_name"].str.len()

# ==========================================
# Length of Email Addresses
# ==========================================

df["email"].str.len()

# ==========================================
# Average Name Length
# ==========================================

df["full_name"].str.len().mean()

np.float64(9.13)

# 📝 Summary

Functions Covered

- `str.lower()`
- `str.upper()`
- `str.title()`
- `str.capitalize()`
- `str.swapcase()`
- `str.len()`

These functions help standardize text formatting before performing analysis.

In the next section, we will learn how to remove unwanted spaces using:

- `str.strip()`
- `str.lstrip()`
- `str.rstrip()`

# ✂️ Removing Unwanted Spaces

---

# 🎯 Objective

Extra spaces are one of the most common problems in text data.

Examples:

```
" John Doe "
"  Sales"
"Pune   "
"  HR  "
```

Although these values may look identical,

Python considers them different because of the extra spaces.

Pandas provides powerful string functions to remove unwanted spaces.

> **Rule #2:** Always remove unnecessary spaces before cleaning text data.

In [517]:
# ==========================================
# Display Original Data
# ==========================================

df["full_name"].head(10)

0       John Smith
1        John Doe
2    Alice@@ Brown
3          Bob Lee
4          Bob Lee
5       John Smith
6        John Doe
7        John Doe
8          Bob Lee
9    Alice@@ Brown
Name: full_name, dtype: str

# ✂️ Remove Leading and Trailing Spaces

The `str.strip()` function removes spaces from both the beginning and the end of a string.

### Syntax

```python
Series.str.strip()
```

In [518]:
# ==========================================
# Remove Leading & Trailing Spaces
# ==========================================

temp_df = df.copy()

temp_df["full_name"] = temp_df["full_name"].str.strip()

temp_df["full_name"].head(10)

# ==========================================
# Remove Spaces from Department
# ==========================================

temp_df = df.copy()

temp_df["department"] = temp_df["department"].str.strip()

temp_df["department"].head(10)

0                HR
1                hr
2    Human Resource
3           Finance
4           Finance
5                HR
6                hr
7                hr
8           Finance
9    Human Resource
Name: department, dtype: str

# ⬅️ Remove Leading Spaces

Sometimes we only want to remove spaces from the beginning.

### Syntax

```python
Series.str.lstrip()
```

In [519]:
# ==========================================
# Remove Leading Spaces
# ==========================================

temp_df = df.copy()

temp_df["full_name"] = temp_df["full_name"].str.lstrip()

temp_df["full_name"].head(10)

0       John Smith
1        John Doe
2    Alice@@ Brown
3          Bob Lee
4          Bob Lee
5       John Smith
6        John Doe
7        John Doe
8          Bob Lee
9    Alice@@ Brown
Name: full_name, dtype: str

# ➡️ Remove Trailing Spaces

Sometimes we only want to remove spaces from the end.

### Syntax

```python
Series.str.rstrip()
```

In [520]:
# ==========================================
# Remove Trailing Spaces
# ==========================================

temp_df = df.copy()

temp_df["full_name"] = temp_df["full_name"].str.rstrip()

temp_df["full_name"].head(10)

0       John Smith
1         John Doe
2    Alice@@ Brown
3          Bob Lee
4          Bob Lee
5       John Smith
6         John Doe
7         John Doe
8          Bob Lee
9    Alice@@ Brown
Name: full_name, dtype: str

# 🔄 Replace Characters

The `str.replace()` function replaces one value with another.

It is one of the most frequently used functions during data cleaning.

### Syntax

```python
Series.str.replace(old, new)
```

In [521]:
# ==========================================
# Replace "-" with Space
# ==========================================

temp_df = df.copy()

temp_df["full_name"] = temp_df["full_name"].str.replace("-", " ")

temp_df["full_name"].head(10)

# ==========================================
# Replace "_" with Space
# ==========================================

temp_df = df.copy()

temp_df["department"] = temp_df["department"].str.replace("_", " ")

temp_df["department"].head(10)

# ==========================================
# Remove "." from Names
# ==========================================

temp_df = df.copy()

temp_df["full_name"] = temp_df["full_name"].str.replace(".", "", regex=False)

temp_df["full_name"].head(10)

# ==========================================
# Remove "," from City
# ==========================================

temp_df = df.copy()

temp_df["city"] = temp_df["city"].str.replace(",", "", regex=False)

temp_df["city"].head(10)

0    Mumbai
1    mumbai
2      Pune
3     Delhi
4     Delhi
5    Mumbai
6    mumbai
7    mumbai
8     Delhi
9      Pune
Name: city, dtype: str

# 🔍 Check if Text Contains a Word

The `str.contains()` function searches for specific text.

### Syntax

```python
Series.str.contains("text")
```

In [522]:
# ==========================================
# Employees from Sales Department
# ==========================================

df[df["department"].str.contains("Sales", case=False, na=False)]

# ==========================================
# Employees Living in Pune
# ==========================================

df[df["city"].str.contains("Pune", case=False, na=False)]

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
9,1010,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
20,1021,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
22,1023,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
30,1031,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
35,1036,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
41,1042,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
44,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
58,1059,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
61,1062,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
66,1067,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
70,1071,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
75,1076,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
76,1077,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
77,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
83,1084,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
87,1088,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
92,1093,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
96,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent

# 🚀 Check Starting Characters

The `str.startswith()` function checks whether a string starts with specific text.

### Syntax

```python
Series.str.startswith("A")
```

In [523]:
# ==========================================
# Names Starting with "A"
# ==========================================

df[df["full_name"].str.startswith("A", na=False)]

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
9,1010,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
20,1021,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
22,1023,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
30,1031,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
35,1036,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
41,1042,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
44,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
58,1059,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
61,1062,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
66,1067,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
70,1071,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
75,1076,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
76,1077,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
77,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
83,1084,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
87,1088,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
92,1093,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
96,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent

# 🚀 Check Ending Characters

The `str.endswith()` function checks whether a string ends with specific text.

### Syntax

```python
Series.str.endswith(".com")
```

In [524]:
# ==========================================
# Gmail Users
# ==========================================

df[df["email"].str.endswith("@gmail.com", na=False)]

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
5,1006,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
9,1010,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
16,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
20,1021,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
22,1023,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
25,1026,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
29,1030,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
30,1031,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
35,1036,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
37,1038,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
41,1042,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
43,1044,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
44,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
46,1047,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
48,1049,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
57,1058,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
58,1059,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
61,1062,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
64,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
66,1067,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
70,1071,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
71,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
72,1073,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
75,1076,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
76,1077,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
77,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
83,1084,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
85,1086,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
87,1088,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
92,1093,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
96,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent

# 📝 Summary

Functions Covered

- `str.strip()`
- `str.lstrip()`
- `str.rstrip()`
- `str.replace()`
- `str.contains()`
- `str.startswith()`
- `str.endswith()`

These functions are essential for removing unwanted spaces, replacing characters, and searching text efficiently.

In the next section, we will learn:

- `str.split()`
- `str.join()`
- `str.slice()`
- `str.extract()`
- `str.cat()`
- `str.repeat()`
- `str.zfill()`
- `str.pad()`
- Regular Expressions (Regex)

# ✂️ Splitting, Joining & Extracting Text

---

# 🎯 Objective

Sometimes a single text column contains multiple pieces of information.

Examples:

```
John Doe
john@gmail.com
EMP-1001
Pune, Maharashtra
```

Instead of keeping everything together,

we can split, extract, combine, and manipulate text using Pandas String Functions.

These functions are extremely useful while cleaning real-world datasets.

> **Rule #3:** Never manually split text. Use Pandas string functions.

In [525]:
# ==========================================
# Display Sample Columns
# ==========================================

df[["full_name", "email"]].head()

       full_name             email
0     John Smith    john@gmail.com
1      John Doe      johndoe@gmail
2  Alice@@ Brown  alice@@gmail.com
3        Bob Lee               NaN
4        Bob Lee               NaN

# ✂️ Split Text using `str.split()`

The `str.split()` function splits a string into multiple parts.

### Syntax

```python
Series.str.split(separator)
```

In [526]:
# ==========================================
# Split Full Name
# ==========================================

df["full_name"].str.split(" ")

# ==========================================
# Split Email
# ==========================================

df["email"].str.split("@")

# ==========================================
# Split Name into Multiple Columns
# ==========================================

temp_df = df.copy()

temp_df[["first_name", "last_name"]] = temp_df["full_name"].str.split(
    " ",
    n=1,
    expand=True
)

temp_df.head()

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks,first_name,last_name
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee,John,Smith
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,IND,4000A,11.0,105,TRUE,NaN,Amit,,,John Doe
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,india,411001,-5.0,-15,1,2.0,Suresh,Excellent,Alice@@,Brown
3,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted,Bob,Lee
4,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted,Bob,Lee

# 📍 Access Split Values

After splitting,

individual parts can be accessed using indexing.

In [527]:
# ==========================================
# First Name
# ==========================================

df["full_name"].str.split().str[0]

# ==========================================
# Last Name
# ==========================================

df["full_name"].str.split().str[-1]

0     Smith
1       Doe
2     Brown
3       Lee
4       Lee
      ...
95      Lee
96    Brown
97      Doe
98      Lee
99      Lee
Name: full_name, Length: 100, dtype: object

# 🔗 Join Strings using `str.cat()`

The `str.cat()` function joins multiple strings together.

### Syntax

```python
Series.str.cat(other)
```

In [528]:
# ==========================================
# Combine Name and Department
# ==========================================

df["full_name"].str.cat(
    df["department"],
    sep=" - "
)

# ==========================================
# Combine Name and City
# ==========================================

df["full_name"].str.cat(
    df["city"],
    sep=", "
)

0      John Smith, Mumbai
1       John Doe , mumbai
2     Alice@@ Brown, Pune
3          Bob Lee, Delhi
4          Bob Lee, Delhi
             ...
95         Bob Lee, Delhi
96    Alice@@ Brown, Pune
97      John Doe , mumbai
98         Bob Lee, Delhi
99         Bob Lee, Delhi
Name: full_name, Length: 100, dtype: str

# ✂️ Extract Text using `str.extract()`

Sometimes we only need a specific part of a string.

`str.extract()` uses Regular Expressions (Regex).

### Syntax

```python
Series.str.extract(pattern)
```

In [529]:
# ==========================================
# Extract Email Username
# ==========================================

df["email"].str.extract(r"(^.*)@")

# ==========================================
# Extract Numbers from Employee ID
# ==========================================

df["employee_id"].astype(str).str.extract(r"(\d+)")

       0
0   1001
1   1002
2   1003
3   1004
4   1004
..   ...
95  1004
96  1003
97  1098
98  1004
99  1100

[100 rows x 1 columns]

# ✂️ Slice Text using `str.slice()`

Extract a specific portion of a string.

### Syntax

```python
Series.str.slice(start, stop)
```

In [530]:
# ==========================================
# First Three Characters
# ==========================================

df["full_name"].str.slice(0,3)

# ==========================================
# Last Four Characters
# ==========================================

df["full_name"].str.slice(-4)

# ==========================================
# First Five Characters of Email
# ==========================================

df["email"].str.slice(0,5)

0     john@
1     johnd
2     alice
3       NaN
4       NaN
      ...
95      NaN
96    alice
97    johnd
98      NaN
99      NaN
Name: email, Length: 100, dtype: str

# 🔁 Repeat Text using `str.repeat()`

Repeats each string multiple times.

### Syntax

```python
Series.str.repeat(n)
```

In [531]:
# ==========================================
# Repeat Name Twice
# ==========================================

df["full_name"].str.repeat(2)

0           John SmithJohn Smith
1            John Doe  John Doe
2     Alice@@ BrownAlice@@ Brown
3                 Bob LeeBob Lee
4                 Bob LeeBob Lee
                 ...
95                Bob LeeBob Lee
96    Alice@@ BrownAlice@@ Brown
97           John Doe  John Doe
98                Bob LeeBob Lee
99                Bob LeeBob Lee
Name: full_name, Length: 100, dtype: str

# 0️⃣ Pad Numbers using `str.zfill()`

Adds leading zeros until a fixed width is reached.

Useful for Employee IDs and Invoice Numbers.

### Syntax

```python
Series.str.zfill(width)
```

In [532]:
# ==========================================
# Employee ID with Leading Zeros
# ==========================================

df["employee_id"].astype(str).str.zfill(6)

0     001001
1     001002
2     001003
3     001004
4     001004
       ...
95    001004
96    001003
97    001098
98    001004
99    001100
Name: employee_id, Length: 100, dtype: str

# 📏 Pad Text using `str.pad()`

Pads a string with characters on the left, right, or both sides.

### Syntax

```python
Series.str.pad(width)
```

In [533]:
# ==========================================
# Left Pad
# ==========================================

df["employee_id"].astype(str).str.pad(
    width=8,
    side="left",
    fillchar="0"
)

# ==========================================
# Right Pad
# ==========================================

df["employee_id"].astype(str).str.pad(
    width=8,
    side="right",
    fillchar="-"
)

# ==========================================
# Both Side Padding
# ==========================================

df["employee_id"].astype(str).str.pad(
    width=10,
    side="both",
    fillchar="*"
)

0     ***1001***
1     ***1002***
2     ***1003***
3     ***1004***
4     ***1004***
         ...
95    ***1004***
96    ***1003***
97    ***1098***
98    ***1004***
99    ***1100***
Name: employee_id, Length: 100, dtype: str

# 🔍 Count Characters

The `str.count()` function counts how many times a pattern appears.

### Syntax

```python
Series.str.count(pattern)
```

In [534]:
# ==========================================
# Count Letter "a"
# ==========================================

df["full_name"].str.count("a")

# ==========================================
# Count "@"
# ==========================================

df["email"].str.count("@")

0     1.0
1     1.0
2     2.0
3     NaN
4     NaN
     ...
95    NaN
96    2.0
97    1.0
98    NaN
99    NaN
Name: email, Length: 100, dtype: float64

# 🔍 Check Numeric Text

Determine whether a string contains only numeric values.

Functions:

- `str.isnumeric()`
- `str.isalpha()`
- `str.isalnum()`

In [535]:
# ==========================================
# Check Numeric Employee IDs
# ==========================================

df["employee_id"].astype(str).str.isnumeric()

# ==========================================
# Check Alphabetic Names
# ==========================================

df["full_name"].str.isalpha()

# ==========================================
# Check AlphaNumeric Values
# ==========================================

df["employee_id"].astype(str).str.isalnum()

0     True
1     True
2     True
3     True
4     True
      ...
95    True
96    True
97    True
98    True
99    True
Name: employee_id, Length: 100, dtype: bool

# 📝 Summary

Functions Covered

- `str.split()`
- `str.cat()`
- `str.extract()`
- `str.slice()`
- `str.repeat()`
- `str.zfill()`
- `str.pad()`
- `str.count()`
- `str.isnumeric()`
- `str.isalpha()`
- `str.isalnum()`

These functions are widely used to split, combine, extract, and validate text data.

In the next (and final) part of this chapter, we will learn **Regular Expressions (Regex)** for advanced text cleaning, including cleaning emails, phone numbers, names, and removing unwanted special characters.

# 🔥 Regular Expressions (Regex) for String Cleaning

---

# 🎯 Objective

Real-world text data is often messy.

Examples:

```
John@123
Rahul!!!
Pune#$
98765-43210
john.doe@gmail.com
```

Regular Expressions (Regex) help us search, extract, validate, and replace text using patterns instead of exact words.

Regex is one of the most powerful tools in Data Cleaning.

> **Rule #4:** Learn Regex patterns—they can save hours of manual cleaning.

# 📖 Common Regex Patterns

| Pattern | Meaning | Example |
|----------|----------|---------|
| `\d` | Any digit | 0-9 |
| `\D` | Non-digit | A, @, # |
| `\w` | Letter, Number, _ | abc123 |
| `\W` | Special Character | @#$ |
| `\s` | White Space | Space, Tab |
| `\S` | Non White Space | A, 1 |
| `^` | Starts With | ^A |
| `$` | Ends With | com$ |
| `+` | One or More | \d+ |
| `*` | Zero or More | A* |
| `.` | Any Character | a.c |

# 🔎 Find Names Containing Numbers

Sometimes names contain invalid characters like:

```
John123
Rahul45
Ankit007
```

Let's find them.

In [536]:
# ==========================================
# Names Containing Numbers
# ==========================================

df[df["full_name"].str.contains(r"\d", na=False)]

Empty DataFrame
Columns: [employee_id, full_name, gender, age, email, phone, department, designation, salary, bonus, experience, joining_date, last_promotion, city, state, country, zipcode, performance_score, attendance, is_active, project_count, manager, remarks]
Index: []

[0 rows x 23 columns]

# 🔎 Find Emails Ending with Gmail

In [537]:
# ==========================================
# Gmail Users
# ==========================================

df[df["email"].str.contains(r"@gmail\.com$", na=False)]

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
5,1006,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
9,1010,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
16,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
20,1021,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
22,1023,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
25,1026,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
29,1030,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
30,1031,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
35,1036,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
37,1038,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
41,1042,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
43,1044,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
44,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
46,1047,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
48,1049,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
57,1058,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
58,1059,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
61,1062,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
64,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
66,1067,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
70,1071,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
71,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
72,1073,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
75,1076,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
76,1077,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
77,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
83,1084,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
85,1086,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
87,1088,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
92,1093,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
96,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent

# 🔎 Find Phone Numbers Having Only Digits

In [538]:
# ==========================================
# Valid Phone Numbers
# ==========================================

df[df["phone"].astype(str).str.match(r"^\d+$", na=False)]

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
3,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
5,1006,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
95,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
97,1098,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
98,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
99,1100,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

# 🧹 Remove Numbers from Names

In [539]:
# ==========================================
# Remove Numbers
# ==========================================

temp_df = df.copy()

temp_df["full_name"] = temp_df["full_name"].str.replace(
    r"\d+",
    "",
    regex=True
)

temp_df["full_name"].head()

0       John Smith
1        John Doe
2    Alice@@ Brown
3          Bob Lee
4          Bob Lee
Name: full_name, dtype: str

# 🧹 Remove Special Characters

In [540]:
# ==========================================
# Remove Special Characters
# ==========================================

temp_df = df.copy()

temp_df["full_name"] = temp_df["full_name"].str.replace(
    r"[^A-Za-z ]",
    "",
    regex=True
)

temp_df["full_name"].head()

0     John Smith
1      John Doe
2    Alice Brown
3        Bob Lee
4        Bob Lee
Name: full_name, dtype: str

# 🧹 Keep Only Numbers

In [541]:
# ==========================================
# Keep Digits Only
# ==========================================

temp_df = df.copy()

temp_df["phone"] = temp_df["phone"].astype(str).str.replace(
    r"\D",
    "",
    regex=True
)

temp_df["phone"].head()

0      9876543210
1           98765
2           12345
3    999999999999
4    999999999999
Name: phone, dtype: str

# ✉️ Validate Email Addresses

In [542]:
# ==========================================
# Valid Emails
# ==========================================

valid_email = df["email"].str.match(
    r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$",
    na=False
)

df[valid_email]

# ==========================================
# Invalid Emails
# ==========================================

invalid_email = ~df["email"].str.match(
    r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$",
    na=False
)

df[invalid_email]

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
6,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
96,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
97,1098,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
98,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
99,1100,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

# 📞 Clean Phone Numbers

Convert

```
98765-43210
98765 43210
+91 9876543210
(98765)43210
```

into

```
9876543210
```

In [543]:
# ==========================================
# Clean Phone Numbers
# ==========================================

temp_df = df.copy()

temp_df["phone"] = temp_df["phone"].astype(str).str.replace(
    r"\D",
    "",
    regex=True
)

temp_df["phone"].head()

0      9876543210
1           98765
2           12345
3    999999999999
4    999999999999
Name: phone, dtype: str

# 👤 Clean Employee Names

Convert

```
john123
JOHN##
John___
```

into

```
John
```

In [544]:
# ==========================================
# Clean Employee Names
# ==========================================

temp_df = df.copy()

temp_df["name"] = (
    temp_df["full_name"]
    .str.replace(r"[^A-Za-z ]", "", regex=True)
    .str.strip()
    .str.title()
)

temp_df["full_name"].head()

0       John Smith
1        John Doe
2    Alice@@ Brown
3          Bob Lee
4          Bob Lee
Name: full_name, dtype: str

# 🏙️ Standardize City Names

In [545]:
# ==========================================
# Clean City Names
# ==========================================

temp_df = df.copy()

temp_df["city"] = (
    temp_df["city"]
    .str.strip()
    .str.title()
)

temp_df["city"].head()

0    Mumbai
1    Mumbai
2      Pune
3     Delhi
4     Delhi
Name: city, dtype: str

# 🏢 Standardize Department Names

In [546]:
# ==========================================
# Clean Department Names
# ==========================================

temp_df = df.copy()

temp_df["department"] = (
    temp_df["department"]
    .str.strip()
    .str.title()
)

temp_df["department"].head()

0                Hr
1                Hr
2    Human Resource
3           Finance
4           Finance
Name: department, dtype: str

# 📋 String Cleaning Cheat Sheet

| Function | Purpose |
|----------|---------|
| `str.lower()` | Lowercase text |
| `str.upper()` | Uppercase text |
| `str.title()` | Title Case |
| `str.capitalize()` | Capitalize first letter |
| `str.swapcase()` | Swap letter cases |
| `str.len()` | Length of string |
| `str.strip()` | Remove spaces |
| `str.lstrip()` | Remove left spaces |
| `str.rstrip()` | Remove right spaces |
| `str.replace()` | Replace text |
| `str.contains()` | Search text |
| `str.startswith()` | Starts with |
| `str.endswith()` | Ends with |
| `str.split()` | Split text |
| `str.cat()` | Join text |
| `str.extract()` | Extract text |
| `str.slice()` | Slice text |
| `str.repeat()` | Repeat text |
| `str.zfill()` | Add leading zeros |
| `str.pad()` | Pad text |
| `str.count()` | Count characters |
| `str.match()` | Match regex |
| `str.isalpha()` | Alphabet only |
| `str.isnumeric()` | Numbers only |
| `str.isalnum()` | Alphanumeric |

# 📌 Chapter 05 Complete ✅

Congratulations! 🎉

You have successfully completed one of the most important chapters in this playbook.

## Functions Covered

- `str.lower()`
- `str.upper()`
- `str.title()`
- `str.capitalize()`
- `str.swapcase()`
- `str.len()`
- `str.strip()`
- `str.lstrip()`
- `str.rstrip()`
- `str.replace()`
- `str.contains()`
- `str.startswith()`
- `str.endswith()`
- `str.split()`
- `str.cat()`
- `str.extract()`
- `str.slice()`
- `str.repeat()`
- `str.zfill()`
- `str.pad()`
- `str.count()`
- `str.match()`
- `str.isalpha()`
- `str.isnumeric()`
- `str.isalnum()`
- Regular Expressions (Regex)

In the next chapter, we will learn **Category Cleaning**, where we'll standardize inconsistent categorical values using functions like `unique()`, `nunique()`, `value_counts()`, `replace()`, and `map()`.