# 📅 Chapter 07 - Date & Time Cleaning

---

# 🎯 Objective

Date and Time columns are among the most important columns in any dataset.

Unfortunately, they are often stored as plain text (Object Data Type).

Examples:

```
2025-01-15
15/01/2025
Jan 15, 2025
01-15-2025
```

Although these values represent dates, Pandas cannot perform date operations until they are converted into the proper datetime format.

After converting dates, we can:

✅ Extract Year

✅ Extract Month

✅ Extract Day

✅ Calculate Date Difference

✅ Sort Chronologically

✅ Filter Date Ranges

✅ Detect Invalid Dates

> **Rule #1:** Always convert date columns to datetime before analysis.

In [1]:
# ==========================================
# 📚 Import Libraries
# ==========================================

import pandas as pd
import numpy as np

In [2]:
# ==========================================
# 📂 Load Dataset
# ==========================================

df = pd.read_csv("dataset/employee_dirty_data.csv")

raw_df = df.copy()

# 🔍 Check Current Data Type

Before converting,

let's inspect the current datatype.

In [3]:
# ==========================================
# Current Data Type
# ==========================================

df["joining_date"].dtype

# ==========================================
# Dataset Information
# ==========================================

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   employee_id        100 non-null    int64
 1   full_name          100 non-null    str
 2   gender             100 non-null    str
 3   age                100 non-null    str
 4   email              52 non-null     str
 5   phone              100 non-null    str
 6   department         100 non-null    str
 7   designation        100 non-null    str
 8   salary             100 non-null    str
 9   bonus              81 non-null     float64
 10  experience         100 non-null    str
 11  joining_date       100 non-null    str
 12  last_promotion     33 non-null     str
 13  city               100 non-null    str
 14  state              100 non-null    str
 15  country            100 non-null    str
 16  zipcode            100 non-null    str
 17  performance_score  100 non-null    float64
 18  attendance         100 non-null    int64
 19  is_active          100 non-null    str
 20  project_count      81 non-null     float64
 21  manager            100 non-null    str
 22  remarks            100 non-null    str
dtypes: float64(3), int64(2), str(18)
memory usage: 18.1 KB

# 🔄 Convert to Datetime

Pandas provides the `pd.to_datetime()` function.

### Syntax

```python
pd.to_datetime(column)
```

In [4]:
# ==========================================
# Convert Joining Date
# ==========================================

temp_df = df.copy()

temp_df["joining_date"] = pd.to_datetime(
    temp_df["joining_date"],
    errors="coerce"
)

temp_df["joining_date"].head()

0   2022-01-15
1          NaT
2          NaT
3          NaT
4          NaT
Name: joining_date, dtype: datetime64[us]

# ⚠️ Handling Invalid Dates

Sometimes the dataset contains invalid values.

Example

```
31/02/2025

abc

Not Available
```

Using

```python
errors="coerce"
```

invalid values automatically become **NaT (Not a Time)**.

In [5]:
# ==========================================
# Invalid Dates become NaT
# ==========================================

temp_df = df.copy()

temp_df["joining_date"] = pd.to_datetime(
    temp_df["joining_date"],
    errors="coerce"
)

temp_df[temp_df["joining_date"].isna()]

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
6,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
96,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
97,1098,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
98,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
99,1100,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

# 📅 Extract Year

In [6]:
# ==========================================
# Extract Year
# ==========================================

temp_df = df.copy()

temp_df["joining_date"] = pd.to_datetime(
    temp_df["joining_date"],
    errors="coerce"
)

temp_df["joining_year"] = temp_df["joining_date"].dt.year

temp_df.head()

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks,joining_year
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee,2022.0
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,,NaN
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent,NaN
3,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted,NaN
4,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted,NaN

# 📅 Extract Month

In [7]:
# ==========================================
# Extract Month
# ==========================================

temp_df["joining_month"] = temp_df["joining_date"].dt.month

temp_df.head()

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks,joining_year,joining_month
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee,2022.0,1.0
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,IND,4000A,11.0,105,TRUE,NaN,Amit,,NaN,NaN
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,india,411001,-5.0,-15,1,2.0,Suresh,Excellent,NaN,NaN
3,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted,NaN,NaN
4,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted,NaN,NaN

# 📅 Extract Month Name

In [8]:
# ==========================================
# Month Name
# ==========================================

temp_df["month_name"] = temp_df["joining_date"].dt.month_name()

temp_df.head()

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,zipcode,performance_score,attendance,is_active,project_count,manager,remarks,joining_year,joining_month,month_name
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee,2022.0,1.0,January
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,4000A,11.0,105,TRUE,NaN,Amit,,NaN,NaN,NaN
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,411001,-5.0,-15,1,2.0,Suresh,Excellent,NaN,NaN,NaN
3,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,110001,9.2,98,Y,5.0,Priya,Promoted,NaN,NaN,NaN
4,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,110001,9.2,98,Y,5.0,Priya,Promoted,NaN,NaN,NaN

# 📅 Extract Day

In [9]:
# ==========================================
# Day
# ==========================================

temp_df["joining_day"] = temp_df["joining_date"].dt.day

temp_df.head()

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,performance_score,attendance,is_active,project_count,manager,remarks,joining_year,joining_month,month_name,joining_day
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,8.5,95,Yes,3.0,Rahul Sharma,Good Employee,2022.0,1.0,January,15.0
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,11.0,105,TRUE,NaN,Amit,,NaN,NaN,NaN,NaN
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,-5.0,-15,1,2.0,Suresh,Excellent,NaN,NaN,NaN,NaN
3,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,9.2,98,Y,5.0,Priya,Promoted,NaN,NaN,NaN,NaN
4,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,9.2,98,Y,5.0,Priya,Promoted,NaN,NaN,NaN,NaN

# 📅 Day Name

In [10]:
# ==========================================
# Day Name
# ==========================================

temp_df["day_name"] = temp_df["joining_date"].dt.day_name()

temp_df.head()

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,attendance,is_active,project_count,manager,remarks,joining_year,joining_month,month_name,joining_day,day_name
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,95,Yes,3.0,Rahul Sharma,Good Employee,2022.0,1.0,January,15.0,Saturday
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,105,TRUE,NaN,Amit,,NaN,NaN,NaN,NaN,NaN
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,-15,1,2.0,Suresh,Excellent,NaN,NaN,NaN,NaN,NaN
3,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,98,Y,5.0,Priya,Promoted,NaN,NaN,NaN,NaN,NaN
4,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,98,Y,5.0,Priya,Promoted,NaN,NaN,NaN,NaN,NaN

# 📅 Extract Weekday Number

In [11]:
# ==========================================
# Weekday Number
# ==========================================

temp_df["weekday"] = temp_df["joining_date"].dt.weekday

temp_df.head()

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,is_active,project_count,manager,remarks,joining_year,joining_month,month_name,joining_day,day_name,weekday
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Yes,3.0,Rahul Sharma,Good Employee,2022.0,1.0,January,15.0,Saturday,5.0
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,TRUE,NaN,Amit,,NaN,NaN,NaN,NaN,NaN,NaN
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,1,2.0,Suresh,Excellent,NaN,NaN,NaN,NaN,NaN,NaN
3,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Y,5.0,Priya,Promoted,NaN,NaN,NaN,NaN,NaN,NaN
4,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Y,5.0,Priya,Promoted,NaN,NaN,NaN,NaN,NaN,NaN

# 📅 Extract Quarter

In [12]:
# ==========================================
# Quarter
# ==========================================

temp_df["quarter"] = temp_df["joining_date"].dt.quarter

temp_df.head()

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,project_count,manager,remarks,joining_year,joining_month,month_name,joining_day,day_name,weekday,quarter
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,3.0,Rahul Sharma,Good Employee,2022.0,1.0,January,15.0,Saturday,5.0,1.0
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,NaN,Amit,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,2.0,Suresh,Excellent,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,5.0,Priya,Promoted,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,5.0,Priya,Promoted,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 📅 Extract Week Number

In [13]:
# ==========================================
# ISO Week Number
# ==========================================

temp_df["week"] = temp_df["joining_date"].dt.isocalendar().week

temp_df.head()

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,manager,remarks,joining_year,joining_month,month_name,joining_day,day_name,weekday,quarter,week
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Rahul Sharma,Good Employee,2022.0,1.0,January,15.0,Saturday,5.0,1.0,2
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,Amit,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Suresh,Excellent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
3,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Priya,Promoted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
4,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Priya,Promoted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>

# 🕒 Extract Hour, Minute & Second

Useful when timestamps are available.

In [14]:
# ==========================================
# Hour
# ==========================================

temp_df["hour"] = temp_df["joining_date"].dt.hour

temp_df.head()

# ==========================================
# Minute
# ==========================================

temp_df["minute"] = temp_df["joining_date"].dt.minute

temp_df.head()

# ==========================================
# Second
# ==========================================

temp_df["second"] = temp_df["joining_date"].dt.second

temp_df.head()

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,joining_month,month_name,joining_day,day_name,weekday,quarter,week,hour,minute,second
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,1.0,January,15.0,Saturday,5.0,1.0,2,0.0,0.0,0.0
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN
3,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN
4,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN

# 📆 Date Difference

Calculate how many days have passed since joining.

In [15]:
# ==========================================
# Days Since Joining
# ==========================================

today = pd.Timestamp.today()

temp_df["days_since_joining"] = (
    today - temp_df["joining_date"]
).dt.days

temp_df.head()

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,month_name,joining_day,day_name,weekday,quarter,week,hour,minute,second,days_since_joining
0,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,January,15.0,Saturday,5.0,1.0,2,0.0,0.0,0.0,1658.0
1,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN
3,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN
4,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN

# 📅 Format Dates

Convert datetime into a custom format.

### Syntax

```python
dt.strftime()
```

In [16]:
# ==========================================
# Format Date
# ==========================================

temp_df["joining_date"].dt.strftime("%d-%m-%Y")

# ==========================================
# Month-Year Format
# ==========================================

temp_df["joining_date"].dt.strftime("%B %Y")

0     January 2022
1              NaN
2              NaN
3              NaN
4              NaN
          ...
95             NaN
96             NaN
97             NaN
98             NaN
99             NaN
Name: joining_date, Length: 100, dtype: str

# 🔍 Filter Dates

In [17]:
# ==========================================
# Employees Joined After 2022
# ==========================================

temp_df[
    temp_df["joining_date"] >= "2022-01-01"
]

# ==========================================
# Employees Joined in 2023
# ==========================================

temp_df[
    temp_df["joining_date"].dt.year == 2023
]

Empty DataFrame
Columns: [employee_id, full_name, gender, age, email, phone, department, designation, salary, bonus, experience, joining_date, last_promotion, city, state, country, zipcode, performance_score, attendance, is_active, project_count, manager, remarks, joining_year, joining_month, month_name, joining_day, day_name, weekday, quarter, week, hour, minute, second, days_since_joining]
Index: []

[0 rows x 35 columns]

# 📋 Date & Time Cheat Sheet

| Function | Purpose |
|----------|---------|
| `pd.to_datetime()` | Convert to datetime |
| `dt.year` | Extract year |
| `dt.month` | Extract month |
| `dt.day` | Extract day |
| `dt.month_name()` | Month name |
| `dt.day_name()` | Day name |
| `dt.weekday` | Weekday number |
| `dt.quarter` | Quarter |
| `dt.isocalendar().week` | Week number |
| `dt.hour` | Hour |
| `dt.minute` | Minute |
| `dt.second` | Second |
| `dt.strftime()` | Format date |

# 📌 Chapter 07 Complete ✅

Congratulations! 🎉

You can now confidently work with date and time data in Pandas.

## Functions Covered

- `pd.to_datetime()`
- `dt.year`
- `dt.month`
- `dt.day`
- `dt.month_name()`
- `dt.day_name()`
- `dt.weekday`
- `dt.quarter`
- `dt.isocalendar().week`
- `dt.hour`
- `dt.minute`
- `dt.second`
- `dt.strftime()`

In the next chapter, we'll learn **📊 Outlier Detection & Treatment**, where we'll identify unusual values using **IQR**, **Z-Score**, and visualization techniques like **Box Plots**. This is one of the most important preprocessing steps before building machine learning models.