# ✅ Chapter 09 - Data Validation & Quality Checks

---

# 🎯 Objective

After cleaning a dataset, we should never assume it is perfect.

Before exporting the final dataset, we must validate its quality.

Data Validation helps answer questions like:

- Are there still missing values?
- Are there duplicate records?
- Are data types correct?
- Are values within expected ranges?
- Are email addresses valid?
- Are phone numbers valid?
- Are categories standardized?

Professional Data Analysts always perform a final validation before delivering a dataset.

> **Rule #1:** Never save a dataset without validating it.

In [50]:
# ==========================================
# 📚 Import Libraries
# ==========================================

import pandas as pd
import numpy as np

In [51]:
# ==========================================
# 📂 Load Dataset
# ==========================================

df = pd.read_csv("dataset/employee_dirty_data.csv")

raw_df = df.copy()

# 🔍 Check Dataset Shape

Always verify the number of rows and columns.

In [52]:
# ==========================================
# Dataset Shape
# ==========================================

df.shape

(100, 23)

# 📋 Dataset Information

Check the final data types and non-null values.

In [53]:
# ==========================================
# Dataset Information
# ==========================================

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   employee_id        100 non-null    int64
 1   full_name          100 non-null    str
 2   gender             100 non-null    str
 3   age                100 non-null    str
 4   email              52 non-null     str
 5   phone              100 non-null    str
 6   department         100 non-null    str
 7   designation        100 non-null    str
 8   salary             100 non-null    str
 9   bonus              81 non-null     float64
 10  experience         100 non-null    str
 11  joining_date       100 non-null    str
 12  last_promotion     33 non-null     str
 13  city               100 non-null    str
 14  state              100 non-null    str
 15  country            100 non-null    str
 16  zipcode            100 non-null    str
 17  performance_score  100 non-null    float64
 18  attendance         100 non-null    int64
 19  is_active          100 non-null    str
 20  project_count      81 non-null     float64
 21  manager            100 non-null    str
 22  remarks            100 non-null    str
dtypes: float64(3), int64(2), str(18)
memory usage: 18.1 KB

# ❓ Check Missing Values

In [54]:
# ==========================================
# Missing Values
# ==========================================

df.isnull().sum()

# ==========================================
# Missing Value Percentage
# ==========================================

(df.isnull().sum() / len(df)) * 100

employee_id           0.0
full_name             0.0
gender                0.0
age                   0.0
email                48.0
phone                 0.0
department            0.0
designation           0.0
salary                0.0
bonus                19.0
experience            0.0
joining_date          0.0
last_promotion       67.0
city                  0.0
state                 0.0
country               0.0
zipcode               0.0
performance_score     0.0
attendance            0.0
is_active             0.0
project_count        19.0
manager               0.0
remarks               0.0
dtype: float64

# 👥 Check Duplicate Records

In [55]:
# ==========================================
# Duplicate Records
# ==========================================

df.duplicated().sum()

# ==========================================
# Display Duplicate Rows
# ==========================================

df[df.duplicated()]

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
4,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
6,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
16,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
18,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
19,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
27,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
31,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
36,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
39,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
44,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
47,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
49,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
50,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
51,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
55,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
64,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
69,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
71,1001,John Smith,Male,28,john@gmail.com,9876543210,HR,Analyst,55000,5000.0,...,Mumbai,Maharashtra,India,400001,8.5,95,Yes,3.0,Rahul Sharma,Good Employee
74,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
77,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
82,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
88,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
91,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
93,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
94,1002,John Doe,male,Thirty,johndoe@gmail,98765,hr,Data Analyst,"$45,000",NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
95,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
96,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
98,1004,Bob Lee,MALE,35,NaN,999999999999,Finance,Manager,75k,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

# 🔄 Validate Data Types

In [56]:
# ==========================================
# Data Types
# ==========================================

df.dtypes

employee_id            int64
full_name                str
gender                   str
age                      str
email                    str
phone                    str
department               str
designation              str
salary                   str
bonus                float64
experience               str
joining_date             str
last_promotion           str
city                     str
state                    str
country                  str
zipcode                  str
performance_score    float64
attendance             int64
is_active                str
project_count        float64
manager                  str
remarks                  str
dtype: object

# 💰 Validate Salary

Salary should always be positive.

In [57]:
# Convert Salary to Numeric
df["salary"] = pd.to_numeric(
    df["salary"],
    errors="coerce"
)

# Now check invalid salaries
df[df["salary"] <= 0]

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
2,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
9,1010,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
20,1021,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
22,1023,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
30,1031,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
35,1036,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
41,1042,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
44,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
58,1059,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
61,1062,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
66,1067,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
70,1071,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
75,1076,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
76,1077,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
77,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
83,1084,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
87,1088,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
92,1093,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
96,1003,Alice@@ Brown,F,-25,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent

# 🎂 Validate Age

Age should be between 18 and 65.

In [58]:
# ==========================================
# Convert Columns to Numeric
# ==========================================

df["age"] = pd.to_numeric(df["age"], errors="coerce")




# ==========================================
# Invalid Age
# ==========================================

df[
    (df["age"] < 18) |
    (df["age"] > 65)
]

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
2,1003,Alice@@ Brown,F,-25.0,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
9,1010,Alice@@ Brown,F,-25.0,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
20,1021,Alice@@ Brown,F,-25.0,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
22,1023,Alice@@ Brown,F,-25.0,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
30,1031,Alice@@ Brown,F,-25.0,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
35,1036,Alice@@ Brown,F,-25.0,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
41,1042,Alice@@ Brown,F,-25.0,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
44,1003,Alice@@ Brown,F,-25.0,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
58,1059,Alice@@ Brown,F,-25.0,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
61,1062,Alice@@ Brown,F,-25.0,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
66,1067,Alice@@ Brown,F,-25.0,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
70,1071,Alice@@ Brown,F,-25.0,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
75,1076,Alice@@ Brown,F,-25.0,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
76,1077,Alice@@ Brown,F,-25.0,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
77,1003,Alice@@ Brown,F,-25.0,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
83,1084,Alice@@ Brown,F,-25.0,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
87,1088,Alice@@ Brown,F,-25.0,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
92,1093,Alice@@ Brown,F,-25.0,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
96,1003,Alice@@ Brown,F,-25.0,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent

# 📧 Validate Email Addresses

In [59]:
# ==========================================
# Invalid Emails
# ==========================================

invalid_email = ~df["email"].str.match(
    r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$",
    na=False
)

df[invalid_email]

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
1,1002,John Doe,male,NaN,johndoe@gmail,98765,hr,Data Analyst,NaN,NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
2,1003,Alice@@ Brown,F,-25.0,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35.0,NaN,999999999999,Finance,Manager,NaN,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35.0,NaN,999999999999,Finance,Manager,NaN,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
6,1002,John Doe,male,NaN,johndoe@gmail,98765,hr,Data Analyst,NaN,NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1004,Bob Lee,MALE,35.0,NaN,999999999999,Finance,Manager,NaN,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
96,1003,Alice@@ Brown,F,-25.0,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
97,1098,John Doe,male,NaN,johndoe@gmail,98765,hr,Data Analyst,NaN,NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
98,1004,Bob Lee,MALE,35.0,NaN,999999999999,Finance,Manager,NaN,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
99,1100,Bob Lee,MALE,35.0,NaN,999999999999,Finance,Manager,NaN,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

# 📞 Validate Phone Numbers

In [60]:
# ==========================================
# Invalid Phone Numbers
# ==========================================

invalid_phone = ~df["phone"].astype(str).str.match(
    r"^\d{10}$",
    na=False
)

df[invalid_phone]

,employee_id,full_name,gender,age,email,phone,department,designation,salary,bonus,...,city,state,country,zipcode,performance_score,attendance,is_active,project_count,manager,remarks
1,1002,John Doe,male,NaN,johndoe@gmail,98765,hr,Data Analyst,NaN,NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
2,1003,Alice@@ Brown,F,-25.0,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
3,1004,Bob Lee,MALE,35.0,NaN,999999999999,Finance,Manager,NaN,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
4,1004,Bob Lee,MALE,35.0,NaN,999999999999,Finance,Manager,NaN,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
6,1002,John Doe,male,NaN,johndoe@gmail,98765,hr,Data Analyst,NaN,NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1004,Bob Lee,MALE,35.0,NaN,999999999999,Finance,Manager,NaN,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
96,1003,Alice@@ Brown,F,-25.0,alice@@gmail.com,ABCDE12345,Human Resource,Developer,-25000.0,2500.0,...,Pune,Maharashtra,india,411001,-5.0,-15,1,2.0,Suresh,Excellent
97,1098,John Doe,male,NaN,johndoe@gmail,98765,hr,Data Analyst,NaN,NaN,...,mumbai,MH,IND,4000A,11.0,105,TRUE,NaN,Amit,
98,1004,Bob Lee,MALE,35.0,NaN,999999999999,Finance,Manager,NaN,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted
99,1100,Bob Lee,MALE,35.0,NaN,999999999999,Finance,Manager,NaN,6000.0,...,Delhi,Delhi,INDIA,110001,9.2,98,Y,5.0,Priya,Promoted

# 🏷️ Validate Categories

Check if category values are standardized.

In [61]:
# ==========================================
# Department Categories
# ==========================================

df["department"].value_counts()

# ==========================================
# Gender Categories
# ==========================================

df["gender"].value_counts()

# ==========================================
# City Categories
# ==========================================

df["city"].value_counts()

city
Delhi     48
mumbai    19
Pune      19
Mumbai    14
Name: count, dtype: int64

# 📅 Validate Dates

Check for invalid or missing dates.

In [62]:
# ==========================================
# Invalid Joining Dates
# ==========================================

df[df["joining_date"].isna()]

Empty DataFrame
Columns: [employee_id, full_name, gender, age, email, phone, department, designation, salary, bonus, experience, joining_date, last_promotion, city, state, country, zipcode, performance_score, attendance, is_active, project_count, manager, remarks]
Index: []

[0 rows x 23 columns]

# 📊 Statistical Validation

Review summary statistics to identify suspicious values.

In [63]:
# ==========================================
# Numerical Summary
# ==========================================

df.describe()

,employee_id,age,salary,bonus,performance_score,attendance,project_count
count,100.000000,81.000000,33.000000,81.00000,100.0000,100.00000,81.000000
mean,1035.240000,19.716049,8939.393939,5006.17284,6.7460,77.44000,3.950617
std,31.416434,25.041084,40151.229273,1443.72311,5.7712,45.10332,1.312452
min,1001.000000,-25.000000,-25000.000000,2500.00000,-5.0000,-15.00000,2.000000
25%,1004.000000,28.000000,-25000.000000,5000.00000,8.5000,95.00000,3.000000
50%,1028.000000,35.000000,-25000.000000,6000.00000,9.2000,98.00000,5.000000
75%,1062.250000,35.000000,55000.000000,6000.00000,9.2000,98.00000,5.000000
max,1100.000000,35.000000,55000.000000,6000.00000,11.0000,105.00000,5.000000

# 🔍 Check Unique Values

In [64]:
# ==========================================
# Unique Value Count
# ==========================================

df.nunique()

employee_id          72
full_name             4
gender                4
age                   3
email                 3
phone                 4
department            4
designation           4
salary                2
bonus                 3
experience            4
joining_date          4
last_promotion        2
city                  4
state                 3
country               4
zipcode               4
performance_score     4
attendance            4
is_active             4
project_count         3
manager               4
remarks               4
dtype: int64

# 📋 Generate Validation Report

In [65]:
# ==========================================
# Validation Report
# ==========================================

validation_report = pd.DataFrame({

    "Missing Values": df.isnull().sum(),

    "Data Type": df.dtypes,

    "Unique Values": df.nunique()

})

validation_report

                   Missing Values Data Type  Unique Values
employee_id                     0     int64             72
full_name                       0       str              4
gender                          0       str              4
age                            19   float64              3
email                          48       str              3
phone                           0       str              4
department                      0       str              4
designation                     0       str              4
salary                         67   float64              2
bonus                          19   float64              3
experience                      0       str              4
joining_date                    0       str              4
last_promotion                 67       str              2
city                            0       str              4
state                           0       str              3
country                         0       str              4
zipcode                         0       str              4
performance_score               0   float64              4
attendance                      0     int64              4
is_active                       0       str              4
project_count                  19   float64              3
manager                         0       str              4
remarks                         0       str              4

# ✅ Final Validation Checklist

Before saving your dataset, verify:

- ✔ No unnecessary missing values
- ✔ No duplicate rows
- ✔ Correct data types
- ✔ Valid email addresses
- ✔ Valid phone numbers
- ✔ Correct age range
- ✔ Positive salary values
- ✔ Standardized categories
- ✔ Valid dates

# 📋 Data Validation Cheat Sheet

| Function | Purpose |
|----------|---------|
| `shape` | Dataset dimensions |
| `info()` | Dataset information |
| `dtypes` | Check data types |
| `isnull()` | Missing values |
| `duplicated()` | Duplicate rows |
| `describe()` | Statistical summary |
| `value_counts()` | Category validation |
| `nunique()` | Count unique values |
| `str.match()` | Validate patterns |

# 📌 Chapter 09 Complete ✅

Congratulations! 🎉

You have successfully learned how to validate a cleaned dataset before using it for analysis or Machine Learning.

## Functions Covered

- `shape`
- `info()`
- `dtypes`
- `isnull()`
- `duplicated()`
- `describe()`
- `value_counts()`
- `nunique()`
- `str.match()`

In the next chapter (**Chapter 10**), we'll learn **Saving & Exporting Clean Data**, including exporting to CSV, Excel, JSON, Parquet, and Pickle with best practices.